import Header from "@/components/layout/Header";
import { main_font } from "./fonts";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/layout/Footer";
import TProvider from "@/components/layout/TProvider";

export const metadata: Metadata = {
  title: "Твердый Знак",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${main_font.className} bg-light dark:bg-dark flex flex-col min-h-screen`}
      >
        <TProvider>
          <Header />
          <main className="grow">{children}</main>
          <Footer />
        </TProvider>
      </body>
    </html>
  );
}
