import Header from "@/components/layout/Header";
import { main_font } from "../fonts/fonts";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Твердый Знак",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${main_font.className} bg-light dark:bg-dark flex flex-col min-h-screen scroll-smooth`}
      >
        <Header />
        <main className="grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
